# Generated by Django 5.2 on 2025-04-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
