# Generated by Django 5.2 on 2025-04-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
