# Generated by Django 5.2 on 2025-04-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=1, default='5.0', max_digits=5),
        ),
    ]
